using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Pulumi;

namespace samcogan.azurenative.containerService
{
    /// <summary>
    /// Arguments to create an AKS cluster
    /// </summary>
    public class ScContainerServiceClusterArgs: ResourceArgs
    {
        /// <summary>
        /// Name of the resource group to create
        /// </summary>
        public Input<string> ResourceGroupName { get; set; }
        /// <summary>
        /// Name of the AKS cluster to create
        /// </summary>
        public Input<string> ClusterName { get; set; }
        /// <summary>
        /// Number of nodes in the cluster
        /// </summary>
        public Input<int> NodeCount { get; set; }

        /// <summary>
        /// Size of the nodes in the cluster
        /// Defaults to "Standard_D4_v3"
        /// </summary>
        public Input<string> NodeSize { get; set; } = "Standard_D4_v3";
        /// <summary>
        /// Address space to use for vNet, autogenerated if not supplied
        /// </summary>
        public Input<string>? AddressSpace { get; set; }
        /// <summary>
        /// Name of the subnet to create, autogenerated if not supplied
        /// </summary>
        public Input<string>? SubnetName { get; set; }
        /// <summary>
        /// Version of AKS to deploy
        /// </summary>
        public Input<string> AKSVersion { get; set; }
    }
}
